### ISSUE TITLE
Support for *.properties files (labels)

### ISSUE THREAD

**Issue by semrola** [imixs/manik-hot-deploy#9]
Does this work for properties files - bundles with labels? I can't seem to make hot deploy work for properties files changes. I am using WF 10.1.

**Comment by rsoika** [comment]
It depends how you load the properties file. Typically a property file is part of the class files and located in the META-INF folder. And this location is not part of the hot-deploy. 

The ignore locations are defined as followed:

```
	private static String[] IGNORE_DIRECTORIES = { "/src/main/resources/",
			"/src/main/java/", "/src/test/resources/", "/src/test/java/",
			"/target/m2e-wtp/", "/target/maven-archiver/", "/META-INF/",
			"/target/application.xml", "/target/test-classes/",
			"/target/classes/", "/WEB-INF/classes/" };
	private static String[] IGNORE_SUBDIRECTORIES = { "/classes/",
			"/src/main/webapp/" };
```
So a file in one of this locations will not be updated. The reason is that I do not know how to trigger Wildfly to re-load a class file. I think this is not possible.
